version: '3'
services:
  db:
    image: 'postgres:10'
    environment:
      POSTGRES_PASSWORD: 1112
      POSTGRES_USER: 'postgres'
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: 'fenglc/pgadmin4'
    ports:
      - "5050:5050"
    links:
      - db:postgres